name: Build_SmartButtons

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Dependencies
        run: |
          brew install ldid

      - name: Setup Theos & SDKs
        run: |
          # تنظيف شامل للمسارات قبل البدء
          rm -rf ~/theos
          # تحميل Theos الأساسي
          git clone --recursive https://github.com/theos/theos.git ~/theos
          # مسح مجلد sdks الفارغ الذي ينشئه Theos تلقائياً لتجنب الخطأ 128
          rm -rf ~/theos/sdks
          # تحميل الـ SDKs في المجلد المخصص لها
          git clone --depth 1 https://github.com/theos/sdks.git ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Tweak
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartButtons-Package
          path: packages/*.deb
