name: Build Alhussaini Dylib UBUNTU

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential toolchain-prefix clang libicu-dev libcurl4-openssl-dev libssl-dev uuid-dev

      - name: Setup Theos & SDK
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          curl -L "https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz" -o sdk.tar.xz
          mkdir -p ~/theos/sdks
          tar -xf sdk.tar.xz -C ~/theos/sdks/
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Dylib
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1
        
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Alhussaini-Dylib
          path: .theos/obj/*.dylib
